apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-native-app
  namespace: cloud-native-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-native-app
  template:
    metadata:
      labels:
        app: cloud-native-app
    spec:
      containers:
        - name: app
          image: gcr.io/eco-analog-461308-e7/cloud-native-app:v1
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb-service:27017/cloudnative"
            - name: PORT
              value: "3000"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-native-app-service
  namespace: cloud-native-app
spec:
  selector:
    app: cloud-native-app
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
